device: auto
out_dir: results
case: pronto
seed: 78
num_workers: 0
print: both

### debug settings
neptune_agg: true
draw_learned_graph: false

### dataset settings
dataset:
  dir: datasets/pronto
  has_adj: false
  normalize: true
  scaler_type: standard
  window_size: 1
  aug_ocvar: true
  use_indep_vars: true
  aug_ocvar_on_node: false
  use_indep_vars: true
  train_file: normal.csv
  test_file: faults.csv
  test_split: 0.4
  val_split: 0.16667

task:
  type: anomaly
  anomaly_score_func: node_scaled
  train_type: mapping
  detection_delay_ts: 30
  anomaly_score_thresh: 0.95
  anomaly_score_sw: 1
  anomaly_score_thresh_mode: val

### default model paramters
model:
  type: fnn
  activation: relu
  do_norm: True
  norm_func: batch
  dropout: 0.
  output_dim: 11
  fnn:
    hidden_dims: [50, 50, 50, 50, 50, 50, 50]

### training paramters
train:
  ckpt_period: 50
  draw_period: 50
  auto_resume: true
  epoch_resume: -1
  ckpt_clean: true
  batch_size: 256
  early_stop_patience: 20
  early_stop_min: 150
  
### optimizer paramters
optim:
  base_lr: 1e-3
  max_epochs: 300
  scheduler: plateau
  factor: 0.9
  patience: 10
  criterion: mse
