device: auto
out_dir: results
case: pronto
seed: 78
num_workers: 0
print: both

### debug settings
neptune_agg: true
neptune_each_run: false
tensorboard_each_run: true

draw_learned_graph: false

### dataset settings
dataset:
  dir: datasets/pronto
  has_adj: false
  normalize: true
  scaler_type: standard
  window_size: 15
  aug_ocvar_on_node: false
  aug_ocvar: true
  use_indep_vars: true
  train_file: normal.csv
  test_file: faults.csv
  horizon: 1
  test_split: 0.4
  val_split: 0.16667

task:
  type: anomaly
  anomaly_score_func: node_scaled
  anomaly_score_metric: mse
  anomaly_score_sw: 1
  metric: first
  level: graph
  train_type: reconst
  anomaly_score_thresh_mode: val
  detection_delay_ts: 30
  track_graph: true

### default model paramters
model:
  type: grelen
  grelen:
    prior: [0.97, 0.03]
    graph_learner_n_hid: 40
    graph_learner_n_head_dim: 20
    graph_learner_head: 2
    num_rnn_layers: 1
    gru_n_dim: 40
    temperature: 0.5
    max_diffusion_step: 2
  dropout: 0.0

### training paramters
train:
  ckpt_period: 20
  draw_period: 20
  auto_resume: true
  epoch_resume: -1
  ckpt_clean: true
  batch_size: 256
  early_stop_patience: 20
  early_stop_min: 150
  
### optimizer paramters
optim:
  base_lr: 1e-3
  max_epochs: 300
  scheduler: plateau
  factor: 0.9
  patience: 10
  criterion: mse