# reverse output order
device: auto
out_dir: results
case: pronto
seed: 78
num_workers: 0
print: both

### debug settings
neptune_agg: true
draw_learned_graph: false

### dataset settings
dataset:
  dir: datasets/pronto
  has_adj: false
  normalize: true
  scaler_type: standard
  window_size: 15
  aug_ocvar: true
  use_indep_vars: true
  aug_ocvar_on_node: false
  train_file: normal.csv
  test_file: faults.csv
  horizon: 1
  test_split: 0.4
  val_split: 0.16667

task:
  type: anomaly
  anomaly_score_func: node_scaled
  level: graph
  train_type: reconst
  anomaly_score_thresh: 0.95
  detection_delay_ts: 30
  anomaly_score_sw: 1
  anomaly_score_thresh_mode: val
  metric: all

### default model paramters
model:
  output_dim: 0
  dropout: 0.
  activation: relu
  norm_func: batch
  type: lstmae
  lstmae:
    n_layers: 2
    hidden_dim: 40

### training paramters
train:
  ckpt_period: 20
  auto_resume: true
  epoch_resume: -1
  ckpt_clean: true
  batch_size: 256
  early_stop_patience: 20
  early_stop_min: 150

### optimizer paramters
optim:
  base_lr: 1e-3
  max_epochs: 305
  scheduler: plateau
  factor: 0.9
  patience: 10
  criterion: mse
