device: auto
out_dir: results
case: toy
seed: 78
num_workers: 0
print: both

neptune_agg: true
neptune_each_run: false

### dataset settings
dataset:
  dir: datasets/toy
  has_adj: false
  normalize: false
  window_size: 15
  aug_ocvar_on_node: true
  train_file: train.csv
  test_file: test.csv

task:
  type: anomaly
  anomaly_score_func: att_scaled
  train_type: reconst
  anomaly_score_thresh: 0.95
  anomaly_score_sw: 1
  detection_delay_ts: 10
  anomaly_score_thresh_mode: val
  metric: all

### default model paramters
model:
  type: dyedgegat
  dyedgegat:
    feat_input_node: 1
    feat_input_edge: 1
    temp_node_embed_dim: 10
    temp_edge_embed_dim: 1
    temp_edge_hid_dim: 20
    gnn_type: gin
    gnn_embed_dim: 20
    num_gnn_layers: 2
    node_encoder_type: gru
    node_encoder_mode: simple
    infer_graph: false
    do_encoder_norm: true
    do_decoder_norm: false
    encoder_norm_type: layer
    decoder_norm_type: layer
    infer_temporal_edge: true
    use_time_encoding: true
    time_dim: 5
    aug_feat_edge_attr: false
    temporal_window: 5
    edge_aggr: dot
    flip_output: true
  dropout: 0.

### training paramters
train:
  ckpt_period: 50
  auto_resume: true
  epoch_resume: -1
  ckpt_clean: true
  batch_size: 64
  early_stop_patience: 20
  early_stop_min: 200


### optimizer paramters
optim:
  base_lr: 1e-3
  max_epochs: 300
  scheduler: none
  criterion: mae