device: auto
out_dir: results
case: toy
seed: 78
num_workers: 0
print: both

### debug settings
neptune_agg: true
neptune_each_run: false
draw_learned_graph: false

### dataset settings
dataset:
  dir: datasets/toy
  has_adj: false
  normalize: false
  window_size: 1
  aug_ocvar_on_node: false
  train_file: train.csv
  test_file: test.csv

task:
  type: anomaly
  anomaly_score_func: node_scaled
  train_type: mapping
  anomaly_score_thresh: 0.95
  anomaly_score_sw: 1
  detection_delay_ts: 10
  anomaly_score_thresh_mode: val

### default model paramters
model:
  type: fnn
  activation: relu
  do_norm: True
  norm_func: batch
  dropout: 0.
  output_dim: 5
  fnn:
    hidden_dims: [20, 10, 10]

### training paramters
train:
  ckpt_period: 50
  draw_period: 50
  auto_resume: true
  epoch_resume: -1
  ckpt_clean: true
  batch_size: 64
  early_stop_patience: 20
  early_stop_min: 150
  
### optimizer paramters
optim:
  base_lr: 1e-3
  max_epochs: 300
  scheduler: none
  criterion: mae